import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

/** Widths of the `<name>-<width>.webp` variants made by `npm run newsletter:variants`. */
export const IMAGE_VARIANT_WIDTHS = [720, 1100];

export interface PublicImage {
  width?: number;
  height?: number;
  /** `srcset` built from `<name>-720.webp` / `<name>-1100.webp` siblings, when they exist. */
  srcset?: string;
}

/**
 * Read the intrinsic size of an image under `public/` at build time so `<img>` can set width/height,
 * and pick up responsive variants generated by `npm run newsletter:variants`.
 */
export async function getPublicImage(publicPath: string, baseUrl = ""): Promise<PublicImage> {
  if (!publicPath.startsWith("/")) return {};
  const file = path.join(process.cwd(), "public", publicPath);
  try {
    const { width, height } = await sharp(file).metadata();
    const { dir, name, ext } = path.parse(publicPath);
    const candidates = IMAGE_VARIANT_WIDTHS.map((w) => ({ w, url: `${dir}/${name}-${w}${ext}` })).filter((v) =>
      fs.existsSync(path.join(process.cwd(), "public", v.url)),
    );
    const srcset = candidates.length
      ? [...candidates.map((v) => `${baseUrl}${v.url} ${v.w}w`), `${baseUrl}${publicPath} ${width}w`].join(", ")
      : undefined;
    return { width, height, srcset };
  } catch {
    return {};
  }
}
